# Generated by Django X.Y on YYYY-MM-DD HH:MM

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),  # Replace with your last migration name
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='frozenState',
            field=models.BooleanField(default=False),
        ),
    ]
